# Generated by Django 5.1 on 2026-06-15 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_date", models.DateField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("call_agent", "Call Agent"),
                            ("revisit", "Revisit Property"),
                            ("request_documents", "Request Documents"),
                            ("negotiate", "Follow Up on Negotiation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_done", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["reminder_date"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quick_note", models.CharField(max_length=500)),
                ("detailed_note", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("water", "Water"),
                            ("legal", "Legal"),
                            ("access", "Access"),
                            ("price", "Price"),
                            ("agent", "Agent"),
                            ("farming", "Farming"),
                            ("tourism", "Tourism"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("weather_notes", models.CharField(blank=True, max_length=200)),
                ("agent_present", models.BooleanField(default=False)),
                ("next_action", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
    ]
