# Generated by Django 5.1 on 2026-06-15 03:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("full_address", models.TextField(blank=True)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("taluka", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                (
                    "state",
                    models.CharField(blank=True, default="Maharashtra", max_length=100),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                (
                    "total_area",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        choices=[
                            ("acres", "Acres"),
                            ("guntha", "Guntha"),
                            ("hectare", "Hectare"),
                            ("sqft", "Square Feet"),
                            ("sqmeter", "Square Meters"),
                        ],
                        default="acres",
                        max_length=20,
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("agricultural", "Agricultural"),
                            ("na", "Non-Agricultural (NA)"),
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "asking_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "expected_negotiated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "price_per_acre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "estimated_market_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("agent_name", models.CharField(blank=True, max_length=200)),
                ("agent_phone", models.CharField(blank=True, max_length=20)),
                ("alternate_contact", models.CharField(blank=True, max_length=200)),
                (
                    "investment_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("rejected", "Rejected"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_visit", "To Visit"),
                            ("visited", "Visited"),
                            ("under_discussion", "Under Discussion"),
                            ("due_diligence", "Due Diligence"),
                            ("negotiating", "Negotiating"),
                            ("purchased", "Purchased"),
                            ("rejected", "Rejected"),
                        ],
                        default="to_visit",
                        max_length=30,
                    ),
                ),
                ("general_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "highway",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "dam",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "town",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "hospital",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "school",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "railway_station",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "airport",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "industrial_zone",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                ("future_infrastructure_notes", models.TextField(blank=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distances",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "distance info",
                "verbose_name_plural": "distance info",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("survey_map", "Survey Map"),
                            ("pdf", "PDF"),
                            ("document", "Document"),
                            ("video", "Video"),
                        ],
                        default="photo",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borewell_available", models.BooleanField(blank=True, null=True)),
                (
                    "borewell_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Depth in feet",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "water_availability_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                ("river_nearby", models.BooleanField(default=False)),
                ("lake_nearby", models.BooleanField(default=False)),
                ("dam_nearby", models.BooleanField(default=False)),
                ("water_comments", models.TextField(blank=True)),
                (
                    "road_access_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "distance_to_main_road",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="km",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "internal_road_condition",
                    models.CharField(blank=True, max_length=200),
                ),
                ("accessibility_notes", models.TextField(blank=True)),
                ("electricity_available", models.BooleanField(blank=True, null=True)),
                ("internet_available", models.BooleanField(blank=True, null=True)),
                (
                    "mobile_network_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
                (
                    "terrain_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("flat", "Flat"),
                            ("sloped", "Sloped"),
                            ("hilly", "Hilly"),
                            ("rocky", "Rocky"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tree_cover_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "scenic_value_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "pollution_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Lower is better",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "noise_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Lower is better",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                ("title_clear", models.BooleanField(blank=True, null=True)),
                ("mutation_complete", models.BooleanField(blank=True, null=True)),
                ("survey_completed", models.BooleanField(blank=True, null=True)),
                ("encumbrances", models.TextField(blank=True)),
                (
                    "development_potential_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "tourism_potential_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "farming_potential_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "weekend_home_potential_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
