# Generated by Django 4.2.30 on 2026-06-16 18:09

import apps.properties.card_config
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_is_default'),
        ('properties', '0002_property_home_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_fields', models.JSONField(default=apps.properties.card_config.default_card_fields)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_card_settings', to='core.project')),
            ],
        ),
    ]
