# Generated by Django 5.2.15 on 2026-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_map_card_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
