# Generated by Django 5.1 on 2026-06-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture / Farmland"),
                            ("commercial", "Commercial"),
                            ("residential", "Residential"),
                            ("international", "International"),
                            ("mixed", "Mixed / Other"),
                        ],
                        default="agriculture",
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=2026)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "name"],
            },
        ),
    ]
